homework 7
mipkasnow/niffler-st4 pull request #4
Opened 2024-01-26 16:51 UTC by mipkasnow

2024-01-28 07:59 UTC, sashkir7 requested changes
Неплохо! Но нужны доработки

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepository.java
> +  void updateCurrencyByUsername(String name, CurrencyValues currency);
Если честно, то хотелось бы увидеть несколько методов на редактирование: auth и userdata БД.

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepository.java
> +  List<UserEntity> getAllUsersData();
Для чего нам метод получения всех пользователей из userdata? 
Просто интересен практический кейс) Если добавили в качестве "поиграться" с коллекциями - то тоже круть!

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +            user.setSurname(resultSet.getString("setsurname"));
setsurname - не опечатка ли?

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUser.java
> +}
Необходимо добавить поля username и password
Согласно заданию "@DbUser(username = "", password = "")"

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +    private final UserEntity user = new UserEntity();
Так делать нельзя! При параллельном запуске тестов возможно возникновение ошибки, которую воспроизвести, отловить и тд крайне сложно

Junit создает ед экземпляр данного расширения. Поэтому для всех потоков будет использоваться (шариться) один экземпляр.

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +    private final UserEntity user = new UserEntity();
Это очень важно. Постарайтесь это прямо прочувствовать
Если нужно, то напишу более детально

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +        userAuth.setPassword(String.valueOf(faker.number().numberBetween(10000, 99999)));
username и password рандомные, если в аннотации значение = ""

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +        userEntities.put("user", user);
Ключи лучше вынести, как static поля

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DeleteDbUser.java
> +}
Лучше объединить с прошлым extension(ом).
И аннотацию также лучше объединить. Например, путем добавления нового поля boolean deleteAfterTest default false

2024-01-28 07:59 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DeleteDbUserExtension.java
> +public class DeleteDbUserExtension implements AfterTestExecutionCallback {
Объединить с прошлым extension

2024-01-28 13:21 UTC, mipkasnow commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepository.java
> +  List<UserEntity> getAllUsersData();
1) Да, хотелось просто немного потренироваться в получение не только одной строки или значения, а списка
2) Изначально подумал, что это могло бы пригодиться в кейсе, где пользователь заходит на страницу all people и сверяет список пользователей с полученным из БД. Однако такой тест я написать не смог из-за бага https://github.com/qa-guru/niffler/issues/85

2024-01-28 13:21 UTC, mipkasnow commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepository.java
> +  void updateCurrencyByUsername(String name, CurrencyValues currency);
Придумаю еще тогда)

2024-01-28 13:22 UTC, mipkasnow commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +            user.setSurname(resultSet.getString("setsurname"));
да, здесь точно опечатался. Кстати довольно странно, думал, что будет ошибка в стиле "не найден столбец", судя по всему просто null прилетел

2024-01-28 13:33 UTC, mipkasnow commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +    private final UserEntity user = new UserEntity();
Спасибо, ошибку понял. Про создание нового инстанса класса для каждого теста знаю, это как раз ключевое отличие JUnit5 от TestNG, в последнем инстанс создается один. Из-за этого создаются риски оставить "мусор" после прохождения теста в поле класса.

А вот с extensions я до этого очень мало работал, поэтому еще не усвоилось

2024-01-29 08:57 UTC, sashkir7 requested changes

2024-01-29 08:57 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUser.java
> +    String username();
Можно добавить значения по умолчанию "" (пустую строку)

2024-01-29 08:57 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +    private UserEntity user = new UserEntity();
Так делать нельзя. Грубая ошибка! 
Почему?

Выше говорили о том, что Junit для каждого теста создает свой экземпляр тестового класса. Это действительно так - и это здорово! Когда мы говорим об extensions, то Junit создает единственный экземпляр такого класса для ВСЕХ тестов. Это означает, что при попытке выполнить тесты параллельно, несколько потоков будут изменять одни и те же объекты, что есть неверно! Поэтому в extension нельзя на уровень класса выносить изменяемые свойства. Все, что так или иначе может быть модифицировано, должно объявляться в методах, а передаваться через store (именно поэтому трату в первом дз мы передавали через хранилище, а не использовались свойство класса для этой цели).

2024-01-29 08:57 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +    private boolean deleteAfterTest;
Так делать, соответственно, тоже нельзя

2024-01-29 08:57 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +            this.userName = "".equals(dbUserData.username()) ? faker.name().firstName() : dbUserData.username();
Можно воспользоваться методом isEmpty (у строки)

2024-01-29 09:27 UTC, mipkasnow commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DbUserExtension.java
> +    private UserEntity user = new UserEntity();
спасибо, осознал этот момент

2024-01-29 15:31 UTC, sashkir7 approved these changes

2024-01-30 08:57 UTC, merged