hw12
mipkasnow/niffler-st4 pull request #9
Opened 2024-02-19 12:02 UTC by mipkasnow

2024-02-21 08:06 UTC, sashkir7 requested changes
Очень важно понимать, что значит и как работает слово static в Java
Разберитесь, пожалуйста

2024-02-21 08:06 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/api/client/SpendApiClient.java
> +        this.faker = new Faker();
Можно и без конструктора объявить 
Просто private final Faker faker = Faker();

2024-02-21 08:06 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/condition/SpendCollectionCondition.java
> +  private static final HashMap<String, List<String>> mapResult = new HashMap<>();
static поля - это поля, которые принадлежат не экземпляру класса, а самом классу. Иными словами, static поля существуют в единственном экземпляре.

Думаю, что проблема должна быть понятна. Если нет, то напишите - постараюсь объяснить более детально

2024-02-21 10:28 UTC, mipkasnow commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/condition/SpendCollectionCondition.java
> +  private static final HashMap<String, List<String>> mapResult = new HashMap<>();
Понял ошибку, при многопоточном запуске эти поля будут в единственном экземпляре и будут перезаписываться разными потоками

2024-02-23 18:30 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/condition/SpendCollectionCondition.java
> +  private static final HashMap<String, List<String>> mapResult = new HashMap<>();
При запуске в один поток - ситуация будет аналогичной.
Все потоки (неважно один или несколько) будут добавлять новые объекты в static коллекцию

2024-02-23 18:30 UTC, sashkir7 approved these changes

2024-02-24 10:24 UTC, merged